
import { Bricolage_Grotesque, Instrument_Serif, Host_Grotesk } from "next/font/google";
import "./globals.css";

const bricolageGrotesk = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesk",
  subsets: ["latin"],
  weight: '400',
  display: 'swap',
});
const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: '400',
  display: 'swap',
});
const hostGrotesk = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
  weight: '400',
  display: 'swap',
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${hostGrotesk.variable} ${instrumentSerif.variable} ${bricolageGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
